### ISSUE TITLE
How to track tag change?

### ISSUE THREAD

**Issue by liyishuai** [coq-community/docker-coq#51]
I run CI with specific OCaml versions like `8.14-ocaml-4.12-flambda`, which disappeared recently.

Current workflow: I should go to Docker Hub and find what OCaml versions are available for 8.14.

Is there a way to get notified of tag changes?

**Comment by erikmd** [comment]
> Current workflow: I should go to Docker Hub and find what OCaml versions are available for 8.14.

OK, looks fine.

> Is there a way to get notified of tag changes?

Currently, yes there's something you can do to this aim: subscribe as a watcher of both

* https://github.com/coq-community/docker-base/watchers (when a new base switch is added)
* https://github.com/coq-community/docker-coq/watchers (each non-trivial change has a corresponding PR)

**Comment by erikmd** [comment]
Anyway, beyond what I said in my previous comment, I could think of automating things further in the short run, namely:

the Coq/OCaml correspondence that appears in https://github.com/coq-community/docker-coq/wiki#ocaml-versions-policy:
```yaml
* Coq dev: 
      # coqorg/coq:dev
      default: ['4.13.1-flambda']
      # coqorg/coq:dev-ocaml-4.14-flambda etc.
      base: ['4.14.0-flambda', '4.13.1-flambda', '4.12.1-flambda', '4.09.1-flambda']
* Coq 8.16+rc1: 
      default: ['4.13.1-flambda']
      base: ['4.14.0-flambda', '4.13.1-flambda', '4.12.1-flambda', '4.09.1-flambda']
 * Coq 8.15.2: 
      default: ['4.07.1-flambda']
      base: ['4.14.0-flambda', '4.13.1-flambda', '4.07.1-flambda', '4.05.0']
 * Coq 8.14.1: 
      default: ['4.07.1-flambda']
      base: ['4.14.0-flambda', '4.13.1-flambda', '4.07.1-flambda', '4.05.0']
…
```
is generated by a (locally-run) shell script.
So, it should be possible to create a GHA or so, which would create dedicated PRs (or notifications)
